### ISSUE TITLE
Time formatters

### ISSUE THREAD

**Issue by baudilio** [tbanel/orgaggregate#8]
The formatting directive ';T' does not seem to work.

**Comment by tbanel** [comment]
You are right. In an Org Mode spreadsheet, we can compute, for instance, the average of durations, and format it with `;T` like this:

```
|    07:45 |
|    13:55 |
|    17:12 |
|----------|
| 12:57:20 |
#+TBLFM: @4$1=vmean(@1..@3);T
```
We would like to have this feature in OrgAggregate, but currently it does not work. As a temporary workaround, we can use an alternate Org Mode syntax which works also in OrgAggregate:

```
#+name: atable
| duration |
|----------|
| 07@ 45'  |
| 13@ 55'  |
| 17@ 12'  |

#+BEGIN: aggregate :table "atable" :cols "vmean(duration)"
| vmean(duration) |
|-----------------|
| 12@ 57' 20."    |
#+END:
```
Instead of `HH:MM:SS`, we write `HH@ MM' SS"`
Actually, this later syntax is the one in use in Calc, the Emacs calculator

**Comment by tbanel** [comment]
Implemented.
`HH:MM` and `HH:MM:SS` style durations are recognized in input tables.
To output those styles, use the `;T`, `;U`, or `;t` formatters.
Wait a few hours for the Melpa repository to be automatically updated.

**Comment by baudilio** [comment]
Done! and I confirm it works.
With many thanks.
